// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckLatex() {
  return window['go']['main']['App']['CheckLatex']();
}

export function ExtractFileText(arg1) {
  return window['go']['main']['App']['ExtractFileText'](arg1);
}

export function GenerateCV(arg1) {
  return window['go']['main']['App']['GenerateCV'](arg1);
}

export function GetAPIKey() {
  return window['go']['main']['App']['GetAPIKey']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function OpenOutputFolder() {
  return window['go']['main']['App']['OpenOutputFolder']();
}

export function SaveAPIKey(arg1) {
  return window['go']['main']['App']['SaveAPIKey'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}
