// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckLatex():Promise<boolean>;

export function ExtractFileText(arg1:string):Promise<string>;

export function GenerateCV(arg1:main.GenerateRequest):Promise<main.GenerateResult>;

export function GetAPIKey():Promise<string>;

export function GetStatus():Promise<main.AppStatus>;

export function GetTemplates():Promise<Array<main.Template>>;

export function OpenOutputFolder():Promise<void>;

export function SaveAPIKey(arg1:string):Promise<void>;

export function SelectFile(arg1:string):Promise<string>;
